### PR TITLE
(SIMP-987) Add initial IPA support

### PR DESCRIPTION
**Pull request by CodePhase**
Here is my initial work to support IPA within SIMP.  Please review and provide feedback.  I'm not quite sure why or what it does, but I had to disable 'pam_access.so nodefgroup' from account and session sections to get logins to work.

---
This change is [Reviewable](https://reviewable.io/reviews/simp/pupmod-simp-pam/13)

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
Thanks for the patch!

The pam_access.so enforced client-level access controls on users and groups using /etc/security/access.conf. We'll be keeping that in place but we might make it optional since IPA also provides this capability.

We'll be reviewing this over at https://gerrithub.io.

**Comment by CodePhase** [comment]
Glad to help out.  I wonder if it would be possible then to adjust /etc/security/access.conf to get this to work properly so we can safely keep the pam_access.so setting in place.  If the line remains in there as it stands IPA fails to authorize users and they can't log in.  I removed the setting as a temporary work around just to get it working.

**Comment by lnemsick-simp** [comment]
I have opened up SIMP-4180 for this issue.

**Comment by lnemsick-simp** [comment]
Thank you for your submission. Resolution of the PAM integration issue you encountered will be addressed in https://simp-project.atlassian.net/browse/SIMP-4180.

**Pull request closed without merging**
